import {createHmac,randomBytes,timingSafeEqual,createHash} from 'node:crypto';
import {readFile} from 'node:fs/promises';
const maxAge=60*60*24*30;
const b64=x=>Buffer.from(x).toString('base64url');
const sign=(payload,secret)=>createHmac('sha256',secret).update(payload).digest('base64url');
function tokenFor(data,secret){const payload=b64(JSON.stringify(data));return `${payload}.${sign(payload,secret)}`}
function verify(token,secret){const [payload,sig]=String(token||'').split('.');if(!payload||!sig)return null;const expected=sign(payload,secret),a=Buffer.from(sig),b=Buffer.from(expected);if(a.length!==b.length||!timingSafeEqual(a,b))return null;const data=JSON.parse(Buffer.from(payload,'base64url'));if(Date.now()/1000-data.iat>maxAge)return null;return data}
async function persist(body,code){const url=Netlify.env.get('SUPABASE_URL'),key=Netlify.env.get('SUPABASE_PUBLISHABLE_KEY');if(!url||!key)return false;const response=await fetch(`${url}/rest/v1/rpc/issue_marketing_coupon`,{method:'POST',headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({p:{...body,code}})});if(!response.ok)throw new Error(`coupon rpc ${response.status}`);return true}
export default async request=>{const secret=Netlify.env.get('COUPON_SIGNING_SECRET');if(!secret)return Response.json({error:'Coupon signing is not configured'},{status:503});if(request.method==='POST'){const body=await request.json();if(body.bot_field)return Response.json({ok:true});if(!body.email||!body.first_name||!body.last_name||!body.delivery_consent)return Response.json({error:'Required profile and delivery consent missing'},{status:400});const reward=body.reward==='part_one'?'part_one':'full_book',code=`SIGNAL60-${randomBytes(4).toString('hex').toUpperCase()}`,data={reward,code,eh:createHash('sha256').update(body.email.toLowerCase()).digest('hex').slice(0,16),iat:Math.floor(Date.now()/1000)};let stored=false;try{stored=await persist(body,code)}catch(e){console.error('coupon persistence failed',e.message)}const token=tokenFor(data,secret);return Response.json({ok:true,code,reward,stored,download_url:`/.netlify/functions/coupon-access?token=${encodeURIComponent(token)}`},{headers:{'Cache-Control':'no-store'}})}if(request.method==='GET'){const data=verify(new URL(request.url).searchParams.get('token'),secret);if(!data)return new Response('Invalid or expired coupon',{status:403});const file=data.reward==='part_one'?'part-one-reader.pdf':'full-reader.pdf',bytes=await readFile(new URL(`./assets/${file}`,import.meta.url));return new Response(bytes,{headers:{'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="the-sixtieth-signal-${data.reward.replace('_','-')}.pdf"`,'Cache-Control':'private, no-store','X-Robots-Tag':'noindex, nofollow'}})}return new Response('Method not allowed',{status:405})};
