const roles=['narrator','cassian','imani','nico','pike','loam','seren','shaal','nara','abena','mira','park','arendt','selene','avel','vaziri','sol','quispe','support_female_science','support_female_official','support_female_civic','support_male_science','support_male_civic','iru_shai_ensemble','unresolved'];
const $=selector=>document.querySelector(selector);let data=null,visible=[],selected=0,decisions={};
const keyFor=()=>`signal-routing-${data?.chapter||'none'}`;
function escapeHtml(value){return String(value||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function loadSaved(){decisions=JSON.parse(localStorage.getItem(keyFor())||'{}')}
function save(){localStorage.setItem(keyFor(),JSON.stringify(decisions));render()}
async function loadChapter(number){const response=await fetch(`/audiobook/routing/chapter-${String(number).padStart(2,'0')}-dialogue-review.json`);if(!response.ok)throw new Error('Routing file unavailable');data=await response.json();loadSaved();selected=0;render()}
function filterSpans(){const mode=$('#filter').value;return data.spans.filter(span=>{const d=decisions[span.dialogue_id];if(mode==='unresolved')return !d||d.speaker==='unresolved';if(mode==='explicit')return span.attribution_method==='explicit_named_tag';if(mode==='approved')return d?.review_status==='approved';return true})}
function render(){if(!data)return;visible=filterSpans();selected=Math.min(selected,Math.max(0,visible.length-1));$('#chapter-title').textContent=`${String(data.chapter).padStart(2,'0')} / ${data.chapter_title}`;$('#visible-count').textContent=visible.length;$('#approved-count').textContent=Object.values(decisions).filter(d=>d.review_status==='approved').length;$('#unresolved-count').textContent=data.spans.filter(s=>!decisions[s.dialogue_id]||decisions[s.dialogue_id].speaker==='unresolved').length;$('#queue').innerHTML=visible.map((s,i)=>{const d=decisions[s.dialogue_id];return `<button class="queue-item ${i===selected?'active':''}" data-index="${i}"><span>${s.dialogue_id}</span><div><p>${escapeHtml(s.text_exact)}</p><em>${d?.speaker||s.speaker||'UNRESOLVED'} · ${d?.review_status||s.attribution_method}</em></div></button>`}).join('');renderInspector()}
function renderInspector(){const span=visible[selected];if(!span){$('#inspector').innerHTML='<p class="empty">No spans match this filter.</p>';return}const d=decisions[span.dialogue_id]||{};$('#inspector').innerHTML=`<p class="eyebrow">${span.dialogue_id} · OFFSETS ${span.start_offset}–${span.end_offset}</p><p class="context">${escapeHtml(span.context_before)}</p><blockquote class="quote">${escapeHtml(span.text_exact)}</blockquote><p class="context">${escapeHtml(span.context_after)}</p><div class="decision"><label>Speaker<select id="speaker">${roles.map(r=>`<option ${r===(d.speaker||span.speaker||'unresolved')?'selected':''}>${r}</option>`).join('')}</select></label><label>Confidence<select id="confidence">${[1,.99,.95,.9,.8,0].map(v=>`<option ${v===Number(d.confidence??span.confidence)?'selected':''}>${v}</option>`).join('')}</select></label><label>Reviewer note<textarea id="note">${escapeHtml(d.note||'')}</textarea></label></div><div class="actions"><button class="approve" id="approve">Approve attribution</button><button class="unresolved" id="unresolved">Mark unresolved</button></div>`;$('#approve').onclick=()=>decide('approved');$('#unresolved').onclick=()=>decide('manual_review_required')}
function decide(status){const span=visible[selected],speaker=status==='approved'?$('#speaker').value:'unresolved';decisions[span.dialogue_id]={dialogue_id:span.dialogue_id,text_sha256:span.text_sha256,speaker,confidence:status==='approved'?Number($('#confidence').value):0,review_status:status,note:$('#note').value,reviewed_at:new Date().toISOString()};save();if(selected<visible.length-1){selected++;render()}}
$('#queue').onclick=e=>{const button=e.target.closest('[data-index]');if(button){selected=Number(button.dataset.index);render()}};
$('#filter').onchange=()=>{selected=0;render()};
$('#chapter').onchange=e=>loadChapter(Number(e.target.value)).catch(error=>alert(error.message));
$('#file').onchange=async e=>{data=JSON.parse(await e.target.files[0].text());loadSaved();selected=0;render()};
$('#export').onclick=()=>{if(!data)return;const payload={schema_version:1,chapter:data.chapter,chapter_sha256:data.chapter_sha256,exported_at:new Date().toISOString(),decisions:Object.values(decisions)};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download=`chapter-${String(data.chapter).padStart(2,'0')}-routing-decisions.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key.toLowerCase()==='j'){selected=Math.min(selected+1,visible.length-1);render()}if(e.key.toLowerCase()==='k'){selected=Math.max(selected-1,0);render()}if(e.key.toLowerCase()==='a')$('#approve')?.click();if(e.key.toLowerCase()==='u')$('#unresolved')?.click()});
for(let i=1;i<=50;i++)$('#chapter').insertAdjacentHTML('beforeend',`<option value="${i}">Chapter ${String(i).padStart(2,'0')}</option>`);loadChapter(1).catch(error=>{$('#inspector').innerHTML=`<p class="empty">${escapeHtml(error.message)}. Run <code>npm run audio:review</code> from the project root.</p>`});
